services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ao
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fastapi_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ao -d fastapi_db -h localhost || exit 1"]
      interval: 3s
      timeout: 3s
      retries: 25
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    ports: ["6379:6379"]

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.docker
    depends_on:
      postgres:
        condition: service_healthy
    working_dir: /app
    entrypoint: ["python", "-m", "alembic"]
    command: ["upgrade", "head"]
    restart: "no"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.docker
    environment:
      OPUS_ROOT: "https://voparis-uws-test.obspm.fr"
      OPUS_SERVICE: "gammapy_source_analysis"
      COOKIE_SECURE: "false"
    working_dir: /app
    volumes:
      - ./:/app
      - ./js/build:/app/js/build:ro
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    command: >
      sh -c "uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    working_dir: /js
    # Dev server with HMR
    ports: ["3000:3000"]
    command: ["npm", "start"]
    depends_on:
      - backend

volumes:
  pgdata:
